// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8sG4xx6YNs3bbdJcNyHVYlVklaBFOW0s',
    appId: '1:106773651198:web:8970c6db09f5c94c2fcfaf',
    messagingSenderId: '106773651198',
    projectId: 'peachypastries-d99ad',
    authDomain: 'peachypastries-d99ad.firebaseapp.com',
    storageBucket: 'peachypastries-d99ad.appspot.com',
    measurementId: 'G-FKJDH7VCN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSlvKnhdOW9ieCb5hlYLU2eyPBrbqMUSQ',
    appId: '1:106773651198:android:d6c19d481601558f2fcfaf',
    messagingSenderId: '106773651198',
    projectId: 'peachypastries-d99ad',
    storageBucket: 'peachypastries-d99ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOLWXWeygY26H8lbKBmgBev_jMtTgg3GM',
    appId: '1:106773651198:ios:a0febf02e7731d6e2fcfaf',
    messagingSenderId: '106773651198',
    projectId: 'peachypastries-d99ad',
    storageBucket: 'peachypastries-d99ad.appspot.com',
    iosBundleId: 'com.amaka.peachypastries2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOLWXWeygY26H8lbKBmgBev_jMtTgg3GM',
    appId: '1:106773651198:ios:a0febf02e7731d6e2fcfaf',
    messagingSenderId: '106773651198',
    projectId: 'peachypastries-d99ad',
    storageBucket: 'peachypastries-d99ad.appspot.com',
    iosBundleId: 'com.amaka.peachypastries2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8sG4xx6YNs3bbdJcNyHVYlVklaBFOW0s',
    appId: '1:106773651198:web:b09619c7691b32552fcfaf',
    messagingSenderId: '106773651198',
    projectId: 'peachypastries-d99ad',
    authDomain: 'peachypastries-d99ad.firebaseapp.com',
    storageBucket: 'peachypastries-d99ad.appspot.com',
    measurementId: 'G-T4XZX8QX49',
  );
}
